
spring:
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=gd6ca4d9178d082_lp13lkrj0e2o73a7_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: admin
    password: Green123456789
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  mapper-locations: mapper/*.xml